name: Build docker images

on:
  push:
    branches: ["s1tbx"]
  pull_request:
    branches: ["s1tbx"]
permissions: # to allow container image pushes
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SNAP_VERSION: "13.0.0"
    steps:
      - uses: actions/checkout@v4
      - name: Cache SNAP installer
        id: cache-snap
        uses: actions/cache@v4
        with:
          path: |
            ./esa-snap_all_linux-${{ env.SNAP_VERSION }}.sh
          key: snap-${{ env.SNAP_VERSION }}
      - name: download SNAP installer (if missing)
        if: steps.cache-snap.outputs.cache-hit != 'true'
        shell: bash
        run: |
          PATH_VERSION="${SNAP_VERSION//0.0/0}"
          wget --continue "https://step.esa.int/downloads/${PATH_VERSION}/installers/esa-snap_all_linux-${SNAP_VERSION}.sh"
      - name: login to github container registry GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push s1 toolbox
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            SNAP_VERSION=${{ env.SNAP_VERSION }}
            RESPONSE_FILE=response-s1.varfile
          tags: ghcr.io/${{ github.repository_owner }}/esa-snap:s1tbx-${{ env.SNAP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push full (S1+S2) snap install
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            SNAP_VERSION=${{ env.SNAP_VERSION }}
            RESPONSE_FILE=response-full.varfile
          tags: ghcr.io/${{ github.repository_owner }}/esa-snap:full-${{ env.SNAP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: test SNAP docker images
        shell: bash
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/esa-snap:full-${{ env.SNAP_VERSION }} /usr/local/snap/bin/gpt -h
          docker run --rm ghcr.io/${{ github.repository_owner }}/esa-snap:s1tbx-${{ env.SNAP_VERSION }} /usr/local/snap/bin/gpt -h
